### ISSUE TITLE
[Request dependency]

### ISSUE THREAD

**Issue by thelabcat** [bottlesdevs/dependencies#92] opened 2022-05-06 00:14 UTC
**Dependency name**: mfc42

**Official link to the download page (not direct download)** https://www.dll-files.com/mfc42.dll.html
IDK if that's real or not, but mfc42 is installable via winetricks.

**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
[A Linux Question from some time ago about mfc42 via winetricks](https://www.linuxquestions.org/questions/linux-software-2/wine-is-missing-mfc42-dll-944132/)

**Comment by mirkobrombin** [comment] 2022-05-06 07:20
Duplicate of #69

**Closed by mirkobrombin** 2022-05-06 07:20 UTC
Labels: request dependency
