### ISSUE TITLE
[Request dependency]

### ISSUE THREAD

**Issue by StephenRynas** [bottlesdevs/dependencies#54] opened 2022-03-03 01:48 UTC
**Dependency name**: Microsoft DirectPlay

**Official link to the download page (not direct download)** https://...
See page 69: 4.2 Network Play
https://files.wargamedesignstudio.com/index.php/s/ZJHZjsBzNry99T7

**Is this dependency compatible with Wine?**
- [X ] I have not tested

**Useful links**

Below is the error message I received when I attempted to connect the game on my local LAN. This was from the "host" game. Maybe that will help out.
![image](https://user-images.githubusercontent.com/99763298/156493432-e30f2d58-2e58-4449-8c8f-c9f13fa85351.png)

https://www.partitionwizard.com/partitionmanager/directplay-windows-10.html
![image](https://user-images.githubusercontent.com/99763298/156478629-386936af-8c14-4cd2-835e-b772bdfe5274.png)

**Comment by mirkobrombin** [comment] 2022-03-03 07:09
Duplicate of #53

**Closed by mirkobrombin** 2022-03-03 07:09 UTC
Labels: request dependency
