### ISSUE TITLE
[Report] msxml6 download failed

### ISSUE THREAD

**Issue by wusaby-rush** [bottlesdevs/dependencies#35] opened 2022-01-27 12:21 UTC
**Which dependency?**
msxml6

**Problem type**
- download failed

**Describe the problem**
download this dependcy alway failed for me,  I run bottles from flatpak

**Comment by mirkobrombin** [comment] 2022-01-27 12:23
Does it works downloading from [here](https://web.archive.org/web/20190122095451/https://download.microsoft.com/download/1/5/8/158F681A-E595-472B-B15E-62B649B1B6FF/msxml6-KB973686-enu-amd64.exe)?

**Comment by mirkobrombin** [comment] 2022-01-27 14:04
Can't reproduce on current unstable. I think this was already fixed in current branch.

**Closed by mirkobrombin** 2022-01-27 14:04 UTC
