### ISSUE TITLE
[Request dependency]

### ISSUE THREAD

**Issue by Jose-Rondon** [bottlesdevs/dependencies#98] opened 2022-05-21 16:33 UTC
**mfc42**: dependency name here

**Official link to the download page (not direct download)** It's a known dependecy compatible with wine and proton, I don't know the usefull link :c

**Is this dependency compatible with Wine?**
- [x ] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
They can be links to guides for its implementation or testing or other. Each reference can be useful to maintainers to implement the dependency.

**Comment by mirkobrombin** [comment] 2022-05-21 17:21
Duplicate of https://github.com/bottlesdevs/dependencies/issues/69#issuecomment-1105477540

**Closed by mirkobrombin** 2022-05-21 17:21 UTC
Labels: request dependency
