### ISSUE TITLE
[Request dependency] .NET 4.5.2

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/dependencies#33] opened 2022-01-21 22:34 UTC
**Dependency name**: dotnet452 Microsoft .NET framework 4.5.2

**Official link to the download page (not direct download)** https://www.microsoft.com/en-US/download/dtails.aspx?id=42642

**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

Some of the programs I am trying to run require .NET 4.5.2 specifically. I see there are already a lot of other versions so hopefully it is easy to add this one as well.

**Comment by mirkobrombin** [comment] 2022-01-29 07:26
Duplicate of #16

**Closed by mirkobrombin** 2022-01-29 07:26 UTC
Labels: request dependency
