### ISSUE TITLE
dotnet35 and dotnet35sp1 fail to install 

### ISSUE THREAD

**Issue by VandrerenErik** [bottlesdevs/dependencies#34] opened 2022-01-23 09:19 UTC
Fail to install with the following problem:
![image](https://user-images.githubusercontent.com/54407345/150672033-8734f9b2-395c-47e2-b98a-2824fee14800.png)

`Arch: win64
Creation_Date: '2022-01-23 09:08:32.279717'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.9.3
Environment: Gaming
Environment_Variables: {}
External_Programs: {}
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- dotnet35sp1
Latest_Executables: []
NVAPI: dxvk-nvapi-v0.5.1
Name: Gaming
Parameters:
    aco_compiler: false
    discrete_gpu: true
    dxvk: true
    dxvk_hud: false
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_level: 5
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    pulseaudio_latency: true
    sync: esync
    use_runtime: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkd3d: false
Path: Gaming
Programs: {}
Runner: caffe-7.0-x86_64
State: 0
Uninstallers:
    arial32: false
    courie32: false
    d3dcompiler_43: false
    d3dcompiler_47: false
    d3dx9: false
    dotnet35sp1: true
    msls31: false
    times32: false
Update_Date: '2022-01-23 09:17:01.383269'
VKD3D: vkd3d-proton-2.5
Versioning: false
Windows: win10
WorkingDir: ''`

**Comment by mirkobrombin** [comment] 2022-01-23 09:23
Duplicate of https://github.com/bottlesdevs/Bottles/issues/944

**Closed by mirkobrombin** 2022-01-23 09:23 UTC
